### ISSUE TITLE
Application not applied

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#1253]
Hello,
I'm trying to deploy my own WebLogic domain using Verrazzano.  
I'm partially following https://verrazzano.io/docs/guides/lift-and-shift/

This is my `application.yaml`. I added a generic component that is a Derby DB. I didn't tested them yet, most probably they are going to not spawn but for the moment it isn't that my problem but the fact that Verrazzano doesn't even try to create them.

```
# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: base-domain-appconf
  namespace: base-domain
  annotations:
    version: v1.0.0
    description: "base_domain application configuration"
spec:
  components:
    - componentName: base-domain-domain
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
              scraper: verrazzano-system/vmi-system-prometheus-0
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            spec:
              rules:
                - hosts:
                    - "base-domain-appconf.base-domain.example.com"
                  paths:
                    # application health-check
                    - path: "/health-check"
                      pathType: Prefix
                    # application app
                    - path: "/app"
                      pathType: Prefix
                    # application saml2slo
                    - path: "/saml2slo"
                      pathType: Prefix
    #- componentName: base-domain-configmap
    - componentName: springboot-component
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: base-domain-domain
  namespace: base-domain
spec:
  workload:
    apiVersion: weblogic.oracle/v8
    kind: Domain
    metadata:
      name: base-domain-domain
      namespace: base-domain
    spec:
      domainUID: base-domain

      # WebLogic Image Tool provides domainHome, domainHomeSourceType, and imageName
      domainHome: /u01/domains/base_domain
      domainHomeSourceType: FromModel
      image: gitlab-registry.cern.ch/anappi/my-stuff/wls-12.2.1.4:3.0

      imagePullSecrets:
        - name: base-domain-registry-credentials
      logHomeEnabled: true
      includeServerOutInPodLog: true
      webLogicCredentialsSecret:
        name: base-domain-weblogic-credentials
      configuration:
        istio:
          enabled: false
        introspectorJobActiveDeadlineSeconds: 900
        model:
          configMap: base-domain-configmap
          domainType: WLS

          # WebLogic Image Tool provides modelHome
          modelHome: /u01/wdt/models

          # encryption for the WDT model and the SystemSerializedIni.data file.
          # used only for model-in-image deployment, can be removed for other types.
          runtimeEncryptionSecret: base-domain-runtime-encryption-secret

        secrets:
          - base-domain-server-adminserver
          - base-domain-server-adminserver-ssl
          - base-domain-server-wlsmanaged1
          - base-domain-server-wlsmanaged1-ssl
          - base-domain-securityconfig-myrealm-cern-ldap-authentication
          - base-domain-securityconfig-myrealm

      clusters:
        - clusterName: cluster1
          serverPod:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: "weblogic.clusterName"
                            operator: In
                            values:
                              - $(CLUSTER_NAME)
                      topologyKey: "kubernetes.io/hostname"
          replicas: 1

      serverPod:
        env:
          - name: JAVA_OPTIONS
            value: "-Dweblogic.StdoutDebugEnabled=false"
          - name: USER_MEM_ARGS
            value: "-Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m "
# ---
# apiVersion: core.oam.dev/v1alpha2
# kind: Component
# metadata:
#   name: base-domain-configmap
#   namespace: base-domain
# spec:
#   workload:
#     apiVersion: v1
#     kind: ConfigMap
#     metadata:
#       name: base-domain-configmap
#       namespace: base-domain
#     data:
#       wdt_jdbc.yaml: |
#         resources:
#           JDBCSystemResource:
            
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: springboot-component
  namespace: base-domain
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: springboot-workload
      namespace: springboot
      labels:
        app: springboot
    spec:
      containers:
      - env:
        - name: JAVADB_HOST
          value: wlsdatabase
        - name: JAVADB_PORT
          value: "10220"
        - name: JAVADB_SCHEMA
          value: WLS_KUBERNETES
        - name: JAVA_HOME
          value: /usr/oracle/jdk-1.8.0_281/
        - name: JAVADB_PASSWORD
          value: my_pwd
        image: gitlab-registry.cern.ch/jeedy/appservers/weblogic/images/v12.2.1.4.191220-1.el7.cern-jdk8-1.8.0-241/derby-db:20.7
        imagePullPolicy: Always
        name: wlsdatabase
        ports:
        - containerPort: 10220
          name: derby-listen
          protocol: TCP
        resources:
          limits:
            memory: 1024M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: wlsdatabase
      imagePullSecrets:
      - name: rdbms
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
  
```

With `kubectl describe application` i get:

```bash
 Message:               cannot apply components: cannot apply workload "base-domain-domain": cannot get object: domains.weblogic.oracle "base-domain-domain" is forbidden: User "system:serviceaccount:verrazzano-system:oam-kubernetes-runtime" cannot get resource "domains" in API group "weblogic.oracle" in th
```

I could fix the clusterrole `oam-kubernetes-runtime` adding the permission to see also the domains but it would be a workaround. 

Cheers,
Antonio
