### ISSUE TITLE
WebLogic Operator Errors

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#1261]
Hello,
I have two errors coming from the WebLogic Operator when I try to apply my own domain.

Error 1: 
```json
{"timestamp":"06-16-2021T15:34:05.288+0000","thread":15,"fiber":"engine-operator-thread-2-fiber-168678","namespace":"base-domain","domainUID":"base-domain","level":"SEVERE","class":"oracle.kubernetes.operator.helpers.DomainValidationSteps$DomainValidationStep","method":"apply","timeInMillis":1623857645288,"message":"Domain base-domain is not valid: RuntimeEncryption secret 'base-domain-runtime-encryption-secret' not found in namespace 'base-domain'\nConfigMap 'base-domain-configmap' specified by 'spec.configuration.model.configMap' not found in namespace 'base-domain'.","exception":"","code":"","headers":{},"body":""}
```
Error 2:

```json
{"timestamp":"06-16-2021T15:36:06.847+0000","thread":26,"fiber":"engine-operator-thread-9-fiber-168720","namespace":"base-domain","domainUID":"base-domain","level":"SEVERE","class":"oracle.kubernetes.operator.helpers.DomainValidationSteps$DomainValidationStep","method":"apply","timeInMillis":1623857766847,"message":"Domain base-domain is not valid: ConfigMap 'base-domain-configmap' specified by 'spec.configuration.model.configMap' not found in namespace 'base-domain'.","exception":"","code":"","headers":{},"body":""}
```

The `Error 1` is because I was omitting the `base-domain-runtime-encryption-secret` secret. I thought initially was defined by WDT when discover the domain, but actually in the docs says that is used at runtime.  Can be instead automatically generated by Verrazzano ? Or will it be useful for something else ? I'm asking to know if this password is important for me or i could just forget after first installation...

Related to the `Error 2`, it is missing the configmap `base-domain-configmap`. Shouldn't be created automatically by Verrazzano ?

The component is there: 
```bash
kubectl get components
NAME                    WORKLOAD-KIND                AGE
base-domain-configmap   ConfigMap                    5h31m
base-domain-domain      VerrazzanoWebLogicWorkload   5h42m
derby-component         ContainerizedWorkload        5h42m
````

But the configmap isn't created.

Am I doing something wrong ?

Cheers,
Antonio

**Comment by bobdonat** [comment]
Hi Antonio,
I assume your domain is up and running.  Can you supply the output from `kubectl describe domain base-domain` command.  My suspicion is that the config map error may be a timing thing where the config map was created after the domain resource was created.  When the config map does get created then the error is resolved.

**Comment by bobdonat** [comment]
I need to get back to you on #1

**Comment by antonionappi88** [comment]
Hi Bob,
this is the output of the domain:

```bash
Status:
  Clusters:
  Conditions:
    Last Transition Time:        2021-06-16T15:36:06.850Z
    Message:                     ConfigMap 'base-domain-configmap' specified by 'spec.configuration.model.configMap' not found in namespace 'base-domain'.
    Reason:                      ErrBadDomain
    Status:                      True
    Type:                        Failed
  Introspect Job Failure Count:  0
  Message:                       ConfigMap 'base-domain-configmap' specified by 'spec.configuration.model.configMap' not found in namespace 'base-domain'.
  Reason:                        ErrBadDomain
  Servers:
  Start Time:  2021-06-16T10:07:36.048Z
Events:        <none>
```

Thanks also for the clarification also on Error 1.

**Comment by bobdonat** [comment]
Antonio,  is the domain up and running?

**Comment by antonionappi88** [comment]
no, it isn't. no pod in the ns

**Comment by bobdonat** [comment]
Could you supply the yaml you using to deploy the application so I can try and reproduce

**Comment by antonionappi88** [comment]
Sorry for the delay:

```yaml
# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: base-domain-appconf
  namespace: base-domain
  annotations:
    version: v1.0.0
    description: "base_domain application configuration"
spec:
  components:
    - componentName: base-domain-domain
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
              scraper: verrazzano-system/vmi-system-prometheus-0
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            spec:
              rules:
                - paths:
                    # application health-check
                    - path: "/health-check"
                      pathType: Prefix
                    # application app
                    - path: "/app"
                      pathType: Prefix
                    # application saml2slo
                    - path: "/saml2slo"
                      pathType: Prefix
    #- componentName: base-domain-configmap
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: base-domain-domain
  namespace: base-domain
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoWebLogicWorkload
    spec:
      template:
        metadata:
          name: base-domain-domain
          namespace: base-domain
        spec:
          domainUID: base-domain

          # WebLogic Image Tool provides domainHome, domainHomeSourceType, and imageName
          domainHome: /u01/domains/base_domain
          domainHomeSourceType: FromModel
          image: gitlab-registry.cern.ch/anappi/my-stuff/wls-12.2.1.4:3.0

          imagePullSecrets:
            - name: base-domain-registry-credentials
          includeServerOutInPodLog: true
          webLogicCredentialsSecret:
            name: base-domain-weblogic-credentials
          configuration:
            introspectorJobActiveDeadlineSeconds: 900
            model:
              configMap: base-domain-configmap
              domainType: WLS

              # WebLogic Image Tool provides modelHome
              modelHome: /u01/wdt/models

              # encryption for the WDT model and the SystemSerializedIni.data file.
              # used only for model-in-image deployment, can be removed for other types.
              runtimeEncryptionSecret: base-domain-runtime-encryption-secret

            secrets:
              - base-domain-server-adminserver
              - base-domain-server-adminserver-ssl
              - base-domain-server-wlsmanaged1
              - base-domain-server-wlsmanaged1-ssl
              - base-domain-securityconfig-myrealm-cern-ldap-authentication
              - base-domain-securityconfig-myrealm

          clusters:
            - clusterName: cluster1
              serverPod:
                affinity:
                  podAntiAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          labelSelector:
                            matchExpressions:
                              - key: "weblogic.clusterName"
                                operator: In
                                values:
                                  - $(CLUSTER_NAME)
                          topologyKey: "kubernetes.io/hostname"
              replicas: 1

          serverPod:
            env:
              - name: JAVA_OPTIONS
                value: "-Dweblogic.StdoutDebugEnabled=false"
              - name: USER_MEM_ARGS
                value: "-Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m "
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: base-domain-configmap
  namespace: base-domain
spec:
  workload:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: base-domain-configmap
      namespace: base-domain
    data:
      wdt_jdbc.yaml: |
        resources:
          JDBCSystemResource:
            'base-domain':
              JdbcResource:
                JDBCDriverParams:
                  # This is the URL of the database used by the WebLogic Server application
                  URL: "jdbc:derby://wlsdatabase:10220/rdbms"
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: derby-component
  namespace: base-domain
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: derby-workload
      namespace: base-domain
      labels:
        app: derby
    spec:
      containers:
      - env:
        - name: JAVADB_HOST
          value: wlsdatabase
        - name: JAVADB_PORT
          value: "10220"
        - name: JAVADB_SCHEMA
          value: WLS_KUBERNETES
        - name: JAVA_HOME
          value: /usr/oracle/jdk-1.8.0_281/
        - name: JAVADB_PASSWORD
          value: my_pwd
        image: gitlab-registry.cern.ch/jeedy/appservers/weblogic/images/v12.2.1.4.191220-1.el7.cern-jdk8-1.8.0-241/derby-db:20.7
        imagePullPolicy: Always
        name: wlsdatabase
        ports:
        - containerPort: 10220
          name: derby-listen
          protocol: TCP
        resources:
          limits:
            memory: 1024M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: wlsdatabase
      imagePullSecrets:
      - name: rdbms
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
  
  ```
