### ISSUE TITLE
WebLogic Console Access

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#1295]
Hello,
I'm following this: https://verrazzano.io/docs/samples/lift-and-shift/.

My domain is up and running with the Admin Server and one Managed Server.

But I'm having problems to access the console. When I try to

curl -L -k  https://base-domain-appconf.base-domain.MY_IP.nip.io/app

I get a 404.

Looking at the Virtual Service CRD.

```yaml
hosts:
  - base-domain-appconf.base-domain.MY_IP.nip.io
  http:
  - match:
    - uri:
        prefix: /health-check
    - uri:
        prefix: /app
    - uri:
        prefix: /saml2slo
    - uri:
        prefix: /console
    route:
    - destination:
        host: base-domain-cluster-cluster1
        port:
          number: 10110
```
The `base-domain-cluster-cluster1` is pointing to the Managed Server.
Of course the console is not served on the Managed server but on the Admin Server.

From managed Server
```
[oracle@base-domain-wlsmanaged1 oracle]$ curl -I -L 10.100.132.238:10110/console
HTTP/1.1 404 Not Found
Connection: close
Date: Fri, 25 Jun 2021 11:16:15 GMT
Content-Length: 1164
Content-Type: text/html; charset=UTF-8
```

From the Admin:
```
[oracle@base-domain-adminserver oracle]$ curl -I -L 10.100.235.86:8001/console
HTTP/1.1 302 Moved Temporarily
Date: Fri, 25 Jun 2021 11:19:11 GMT
Location: http://10.100.235.86:8001/console/
Content-Type: text/html

HTTP/1.1 302 Moved Temporarily
Date: Fri, 25 Jun 2021 11:19:11 GMT
Location: http://10.100.235.86:8001/console/login/LoginForm.jsp
Content-Type: text/html
Set-Cookie: ADMINCONSOLESESSION=5ZpC5SbigB8qIak9EtqlXtQQyqEQfZ7oXXmLNc_D17kc2hPM6gDg!6595844; path=/console/; HttpOnly

HTTP/1.1 200 OK
Cache-Control: no-cache
Date: Fri, 25 Jun 2021 11:19:11 GMT
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Content-Type-Options: nosniff
Set-Cookie: ADMINCONSOLESESSION=wSpC5Sbm12hO-2Y3UEwoMOfzPGMim-gTnhRit0Fe3gkzgLanTzFE!6595844; path=/console/; HttpOnly
Content-Language: en-US
X-XSS-Protection: 1;mode=block
X-Frame-Options: DENY
```
          
Now my question is how configure this. The ingress trait (if I understood correctly) is one to one with a component. The WebLogic domain is one component (with Admin and Managed) so I cannot really describe this via Ingress Trait.

The other option would be to serve the console on the Managed Server ? Is it possible ? Never done something like that.

Or maybe I'm missing something ?

Thanks
Antonio
