### ISSUE TITLE
Problem to create custom WebLogic domain

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#339]
Hello there,
I'm facing an issue while I try to deploy a custom WebLogic Domain using Verrazzano.
I'm following https://github.com/verrazzano/examples/blob/master/todo-list/README.md.

I had my domain and I used WDT to discover the domain and get automatically the model and binding YAML files.

I changed the `create_k8s_secrets.sh` script in order to create all my passwords defined in the wdt model. Run it and then i tried to install the model and then the binding. 

The introspect job fails and it isn't able to create the WebLogic domain: 

```bash
Issue Log for createDomain version 1.9.6 running WebLogic version 12.2.1.4.0 offline mode:

SEVERE Messages:

        1. WLSDPLY-01739: Error: Could not resolve secret token "basedomain-server-adminserver:password". Known secrets include: '__WEBLOGIC-CREDENTIALS__:password', '__WEBLOGIC-CREDENTIALS__:username', '__weblogic-credentials__:password', '__weblogic-credentials__:username'
        2. WLSDPLY-20004: createDomain variable substitution failed: Error: Could not resolve secret token "basedomain-server-adminserver:password". Known secrets include: '__WEBLOGIC-CREDENTIALS__:password', '__WEBLOGIC-CREDENTIALS__:username', '__weblogic-credentials__:password', '__weblogic-credentials__:username'

Total:       WARNING :     0    SEVERE :     2
```

I have impression that is looking for the password and username in the secret `basedomain-server-adminserver` but this secret it doesn't have that kind of data. It is instead the `weblogic-credential` to have them.

Here what I have in the `create_k8s_secrets.sh` script:

```bash
# Update <admin-user> and <admin-password> for weblogic-credentials
create_paired_k8s_secret weblogic-credentials weblogic welcome1

# # Update <password> for server-adminserver
create_k8s_secret server-adminserver welcome2
```

and this how the two secret looks like:

```bash
apiVersion: v1
data:
  password: my_password_base64
kind: Secret
metadata:
  creationTimestamp: "2020-10-21T09:29:20Z"
  labels:
    weblogic.domainUID: basedomain
  name: basedomain-server-adminserver
  namespace: basedomain-ns
type: Opaque
```

```yaml
apiVersion: v1
data:
  password: my_password_base64
  username: my_user_base64
kind: Secret
metadata:
  creationTimestamp: "2020-10-21T09:29:08Z"
  labels:
    weblogic.domainUID: basedomain
  name: basedomain-weblogic-credentials
  namespace: basedomain-ns
type: Opaque
```

I can also see that in the model.yaml I have

```yaml
webLogicCredentialsSecret:
          name: basedomain-weblogic-credentials
```

Am I doing something wrong ? 

Thanks,
Antonio

**Comment by ddsharpe** [comment]
It looks like the secrets were not created in the pod.  Everything else looks good.  @antonionappi88  Can you share your two generated yaml files from WDT?

**Comment by antonionappi88** [comment]
Here they are:

Model:
```
kind: VerrazzanoModel
metadata:
  name: basedomain-model
  namespace: default
spec:
  description: "basedomain System"
  weblogicDomains:
    - name: "basedomain"
      domainCRValues:
        domainUID: basedomain
        domainHome: /u01/domains/base_domain
        image: gitlab-registry.cern.ch/anappi/my-stuff/wls-12.2.1.4:2.0
        webLogicCredentialsSecret:
          name: basedomain-weblogic-credentials
        imagePullSecrets:
          - name: ocir
        logHomeEnabled: false
        logHome: /u01/domains/base_domain/logs
        clusters:
          - clusterName: cluster1
            replicas: 1
        serverPod:
          env:
            - name: JAVA_OPTIONS
              value: "-Dweblogic.StdoutDebugEnabled=false"
            - name: USER_MEM_ARGS
              value: "-Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m "
        configuration:
          model:
            domainType: WLS
      connections:
        - ingress:
            - name: basedomain-ingress
              match:
                - uri:
                    prefix: "/todo"

```
Binding
```yaml
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoBinding
metadata:
  name: basedomain-binding
  namespace: default
spec:
  description: "basedomain binding"
  modelName: basedomain-model
  weblogicBindings:
    - name: "basedomain"
  placement:
    - name: local
      namespaces:
        - name: "basedomain-ns"
          components:
            - name: basedomain
  ingressBindings:
    - name: "basedomain-ingress"
      dnsName: "*"
```

**Comment by ddsharpe** [comment]
@antonionappi88 We need to change the Verrazzano operator to automatically propagate the secrets.  Also, I think we can teach WDT's vz target to put those secrets in the Verrazzano model so that you don't need to.

**Comment by antonionappi88** [comment]
@ddsharpe  just to clarify since I'm a bit blocked at moment. Should I wait for a fix right ? Or is there a workaround that I can put in place to skip this ?

Thanks,
Antonio

**Comment by fredtibbitts** [comment]
@antonionappi88 we have a fix for this problem, however it will take a bit of time before the updated Verrazzano Operator image is officially released. In the meantime, if you would like to install the updated image in your cluster, you can do that manually.

If you are using the 0.5.0 release of Verrazzano, do the following:
1. Run the uninstall script to remove the Verrazzano Operator: https://github.com/verrazzano/verrazzano/blob/v0.5.0/uninstall/uninstall-steps/3-uninstall-verrazzano.sh.
1. Edit this line: https://github.com/verrazzano/verrazzano/blob/v0.5.0/install/chart/values.yaml#L16 and replace the version with 0.6.0-20201203172419-8204a25. 
1. Run the install script to upgrade the operator: https://github.com/verrazzano/verrazzano/blob/v0.5.0/install/3-install-verrazzano.sh.

In your model YAML file, you specify the names of the secrets to copy from the default namespace into your WLS domain under `domainCRValues/configuration/secrets`. For example:

```
     - name: test-domain
       domainCRValues:
         configuration:
           secrets:
             - my-secret
             - another-secret
     ...
```
