### ISSUE TITLE
RDBMS store as generic component

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#578]
Hello,

I'm trying to deploy a WebLogic Domain together with a RDBMS store(as generic component). But I'm not able to make it working. 
The issue is that even if the RDBMS store is up and running doesn't accept connections.

```bash
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name     Timer
tcp        0      0 10.244.0.80:10220       0.0.0.0:*               LISTEN      542/java             off (0.00/0/0)
```
When I try to connect(even from the same pod) with the service name or even with the container IP it doesn't work.

```bash
[wls@wlsdatabase ~]$ ${DERBY_INSTALL}/bin/ij /tmp/createdb.sql
ij version 10.14
ij> connect 'jdbc:derby://wlsdatabase:10220/rdbms;user=WLS_KUBERNETES;create=true';
ERROR 08006: A communications error has been detected: Connection reset.
```

I have impression that the envoy container is resetting the connection.

```
[Envoy (Epoch 0)] [2021-02-02 09:25:08.989][28][debug][filter] [src/envoy/tcp/mixer/filter.cc:174] [C1138] Called tcp filter onEvent: 1 upstream 127.0.0.1:10220
[Envoy (Epoch 0)] [2021-02-02 09:25:08.990][28][debug][filter] [src/istio/control/client_context_base.cc:139] Report attributes: attributes {
  key: "connection.duration"
  value {
    duration_value {
      nanos: 845427
    }
  }
}
attributes {
  key: "connection.event"
  value {
    string_value: "close"
  }
}
```
I have been debugging the pool and looks like there aren't available connection(but the istio-proxy is started with concurrency=2)
```bash
Envoy (Epoch 0)] [2021-02-02 09:43:34.917][28][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:364] [C1494] connecting
[Envoy (Epoch 0)] [2021-02-02 09:43:34.917][28][debug][pool] [external/envoy/source/common/tcp/conn_pool.cc:109] queueing request due to no available connections
```

Do you have any suggestion on how workaround this issue ?

Thanks,
Antonio

P.s. Below you can find  my model and binding:

```yaml
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoModel
metadata:
  name: base-domain-model
  namespace: default
spec:
  weblogicDomains:
    - name: "base-domain"
      domainCRValues:
        domainUID: base-domain
        domainHome: /u01/domains/base_domain
        image: my_image
        webLogicCredentialsSecret:
          name: base-domain-weblogic-credentials
        imagePullSecrets:
          - name: ocir
        logHomeEnabled: false
        logHome: /u01/domains/base_domain/logs
        clusters:
          - clusterName: cluster1
             replicas: 1
        serverPod:
          # an (optional) list of environment variable to be set on the servers
          env:
            - name: JAVA_OPTIONS
              value: "-Dweblogic.StdoutDebugEnabled=false"
            - name: USER_MEM_ARGS
              value: "-Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m "
        configuration:
          model:
            domainType: WLS
          secrets:
          - base-domain-server-adminserver
          - base-domain-server-adminserver-ssl
          - base-domain-server-wlsmanaged1
          - base-domain-server-wlsmanaged1-ssl
          #- base-domain-securityconfig-myrealm-cern-ldap-authentication too long
          - base-domain-securityconfig-myrealm-cern-ldap-auth
          - base-domain-securityconfig-myrealm
      connections:
        - ingress:
            - name: base-domain-ingress
              match:
                - uri:
                    prefix: "/todo"
        - database:
            - target: wlsdatabase
              datasourceName: NO_NAME_0
  genericComponents:
    - name: "wlsdatabase"
      replicas: 1
      fluentdEnabled: false
      deployment: 
        containers:
        - env:
          - name: JAVADB_HOST
            value: wlsdatabase
          - name: JAVADB_PORT
            value: "10220"
          - name: JAVADB_SCHEMA
            value: WLS_KUBERNETES
          - name: JAVA_HOME
            value: /usr/oracle/jdk-1.8.0_241/
          - name: JAVADB_PASSWORD
            value: "MY_PWD"
          image: MY_DOCKER_IMAGE
          imagePullPolicy: Always
          name: wlsdatabase
          ports:
          - containerPort: 10220
            name: derby-listen
            protocol: TCP
          resources:
            limits:
              memory: 1024M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        hostname: wlsdatabase
        imagePullSecrets:
        - name: rdbms
```

Binding:

```yaml
apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoBinding
metadata:
  name: base-domain-binding
  namespace: default
spec:
  description: "base-domain binding"
  modelName: base-domain-model
  weblogicBindings:
    - name: "base-domain"
  placement:
    - name: local
      namespaces:
        - name: "base-domain-ns"
          components:
            - name: base-domain
            - name: wlsdatabase
  databaseBindings: 
    - name: wlsdatabase
      url: jdbc:derby://wlsdatabase:10220/rdbms
      credentials: rdbms-credentials
  ingressBindings:
    - name: "base-domain-ingress"
      dnsName: "*"
```

**Comment by ddrechse** [comment]
Hi Antonio,
I am going take a look at your issue.  What is image: MY_DOCKER_IMAGE?
Tnx

**Comment by ddrechse** [comment]
Also, i would like to see the svc entry for derby
kubectl get svc -n mywls_and_derby_install_namespace
Tnx
And the deployments 
kubectl get deploy -n mywls_and_derby_install_namespace

**Comment by ddrechse** [comment]
A few more things, whats the Dockerfile look like that you used to create the Derby container?
And, any errors in the derby log
k logs verrazzano-derby-7b5b4557bb-rvwg8 -n derby verrazzano-derby   for example

Tnx

**Comment by antonionappi88** [comment]
Hi @ddrechse,

Sorry the image is in our private registry. 
Here my Dockerfile

```
FROM gitlab-registry.cern.ch/jeedy/appservers/weblogic/rpm-images/v12.2.1.4.210119-0.el7.cern-jdk8-1.8.0-281

ENV DERBY_OPTS="-Dderby.system.home=/var/lib/derby" \
    DERBY_SYSTEM_DIR="/var/lib/derby"

# JEEDY_MIDDLEWARE_DIR Oracle Middleware installation dir
RUN chmod -R ug+x ${JEEDY_MIDDLEWARE_DIR}/wlserver/common/derby/bin && \
    mkdir -p /var/lib/derby && \
    chown -R wls:ci /var/lib/derby

COPY scripts/configure_db.sh /home/wls/configure_db.sh
COPY scripts/startDB.sh /home/wls/startDB.sh

RUN touch /ORA/dbs01/syscontrol/etc/json/syscontrol.json 
USER wls
WORKDIR /home/wls

CMD /home/wls/startDB.sh
```


The two scripts are:

startDB.sh
```bash
#!/usr/bin/env bash

# Configure the DB using the env variables.
/home/wls/configure_db.sh

# Start the Derby DB
# The noSecurityManager flag is needed because otherwise it will display this error :
# The file or directory /var/lib/derby could not be created due to a security exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/derby" "write").
# By default the Security Manager allow just read operations to the filesystem.
${DERBY_INSTALL}/bin/startNetworkServer -noSecurityManager -h "${JAVADB_HOST}" -p "${JAVADB_PORT}"
```

and configure_db.sh
```bash
#!/usr/bin/env bash

set -x
# Check if it already runs!
ps -ef | grep derby | grep -v grep
if [ $? -eq 0 ]; then
	echo "Derby seems to be already running! Please clean and run again!"
	exit 1
fi
# This should come from the outside - GitlabCI variables
##########################
#JAVADB_HOST=localhost
#JAVADB_PASSWORD=password123^
#JAVADB_PORT=10200
#JAVADB_SCHEMA="WLS_KUBERNETES"
##########################
${DERBY_INSTALL}/bin/startNetworkServer -noSecurityManager -h ${JAVADB_HOST} -p ${JAVADB_PORT} &
sleep 15
# Create a script to initialize the database
SCRIPT="connect 'jdbc:derby://$JAVADB_HOST:${JAVADB_PORT}/rdbms;user=${JAVADB_SCHEMA};create=true';
run '${JEEDY_MIDDLEWARE_DIR}/wlserver/server/lib/rdbms_security_store_derby.sql';
CALL SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY( 'derby.user.${JAVADB_SCHEMA}', '${JAVADB_PASSWORD}');
"
# Add to the
echo "${SCRIPT}" > /tmp/createdb.sql
# Run the script!
output=$(${DERBY_INSTALL}/bin/ij /tmp/createdb.sql)
echo "${output}"
if [[ "${output}" == *"IJ ERROR"* ]]; then
	echo "ERROR running Derby script!"
	exit 1
fi
# Create the properties file
PROPERTIES="derby.connection.requireAuthentication=true
derby.authentication.provider=BUILTIN"
echo "${PROPERTIES}" > ${DERBY_SYSTEM_DIR}/derby.properties
# Restart DB!
${DERBY_INSTALL}/bin/stopNetworkServer -noSecurityManager -h ${JAVADB_HOST} -p ${JAVADB_PORT} &

```

**Comment by antonionappi88** [comment]
Instead for the K8s resources:
Service
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: verrazzano.io
    verrazzano.binding: base-domain-binding
    verrazzano.cluster: local
  name: wlsdatabase
  namespace: base-domain-ns
spec:
  clusterIP: 10.96.5.196
  ports:
  - name: derby-listen
    port: 10220
    protocol: TCP
    targetPort: 10220
  selector:
    app: wlsdatabase
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io/path: /metrics
    prometheus.io/port: "10220"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: verrazzano.io
    verrazzano.binding: base-domain-binding
    verrazzano.cluster: local
  name: wlsdatabase
  namespace: base-domain-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wlsdatabase
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10220"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: wlsdatabase
    spec:
      containers:
      - env:
        - name: JAVADB_HOST
          value: wlsdatabase
        - name: JAVADB_PORT
          value: "10220"
        - name: JAVADB_SCHEMA
          value: WLS_KUBERNETES
        - name: JAVA_HOME
          value: /usr/oracle/jdk-1.8.0_281/
        - name: JAVADB_PASSWORD
          value: my_pwd
        image: gitlab-registry.cern.ch/jeedy/appservers/weblogic/images/v12.2.1.4.191220-1.el7.cern-jdk8-1.8.0-241/derby-db:20.7
        imagePullPolicy: Always
        name: wlsdatabase
        ports:
        - containerPort: 10220
          name: derby-listen
          protocol: TCP
        resources:
          limits:
            memory: 1024M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostname: wlsdatabase
      imagePullSecrets:
      - name: rdbms
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
